# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
      - match:
          dependency_type: "development"
    commit_message:
      include_scope: true
      prefix: "Build"
    default_labels:
      - "dependency"
      - "Changed"