#!/bin/sh

# The hook should exit with non-zero status after issuing
# an appropriate message if it wants to stop the commit.
#
# https://rushjs.io/pages/maintainer/git_hooks/

echo --------------------------------------------
echo Starting Git hook: pre-commit

yarn pretty-quick --staged

yarn sort-package-json

echo Finished Git hook: pre-commit
echo --------------------------------------------
