# This action will automatically close issues fixed in
# pull requests that doesn't target the default branch.

name: Auto Close Fixed Issues
on:
    pull_request_target:
        types: [closed]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
              with:
                egress-policy: audit

            - uses: bubkoo/auto-close-fixed-issues@d87a73261d3881451f5b35a80cfe0eaed3e95931 # v1.1.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  comment: |
                      This issue was closed by #{{ pr }}.
