# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Release"

on:
  push:
    branches:
      - ([0-9])?(.{+([0-9]),x}).x
      - main
      - next
      - next-major
      - alpha
      - beta

permissions:
  contents: read

jobs:
  semantic-release:
    name: "Semantic Release"

    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: "Semantic Release"
        uses: cycjimmy/semantic-release-action@5982a02995853159735cb838992248c4f0f16166 # v2.7.0
        with:
          semantic_version: 17.0.7
          extra_plugins: |
            @semantic-release/changelog@^5.0.1
            @semantic-release/git@^9.0.0
            @google/semantic-release-replace-plugin@^1.0.0
            conventional-changelog-conventionalcommits@^4.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_GITHUB_TOKEN }}
