# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Tests"

on: [push]

permissions:
  contents: read

jobs:
  test:
    name: "Tests"

    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js 12.x
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 12.x

      - name: set git credentials
        run: |
          git config --local user.email "d.bannert@anolilab.de"
          git config --local user.name "Daniel Bannert"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: yarn install

      - name: lint
        run: yarn run lint

      - name: build
        run: yarn run build && yarn run pack

      - name: test
        run: yarn run test

      - name: "Send code coverage report to Codecov.io"
        uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192 # v1.5.2
