name: "test"
on: ["pull_request", "push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: "Setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: "Cache dependencies"
        uses: actions/cache@v1
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-

      - name: "Install dependencies"
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline

      - run: npm run all

      - name: "Send code coverage report to Codecov.io"
        uses: codecov/codecov-action@v1
